//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KHOpenApi.NET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KHOpenApi.NET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10=현재가
        ///11=전일대비
        ///12=등락율
        ///13=누적거래량
        ///14=누적거래대금
        ///15=거래량(+는 매수체결, -는 매도체결)
        ///16=시가
        ///17=고가
        ///18=저가
        ///19=종가
        ///20=체결시간
        ///21=호가시간
        ///22=일자
        ///23=예상체결가
        ///24=예상체결수량
        ///25=전일대비기호
        ///26=전일거래량대비(계약,주)
        ///27=(최우선)매도호가
        ///28=(최우선)매수호가
        ///29=거래대금증감
        ///30=전일거래량대비(비율)
        ///31=거래회전율
        ///32=거래비용
        ///33=5일평균가격
        ///34=10일평균가격
        ///35=20일평균가격
        ///36=NAV
        ///37=NAV전일대비
        ///38=NAV등락율
        ///39=추적오차율
        ///40=괴리율
        ///41=매도호가1
        ///42=매도호가2
        ///43=매도호가3
        ///44=매도호가4
        ///45=매도호가5
        ///46=매도호가6
        ///47=매도호가7
        ///48=매도호가8
        ///49=매도호가9
        ///50=매도호가10
        ///51=매수호가1
        ///52=매수호가2
        ///53=매수호가3
        ///54=매수호가4
        ///55=매수호가5
        ///56=매수호가6
        ///57=매수호가7
        ///58=매수호가8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FID_KORNAME {
            get {
                return ResourceManager.GetString("FID_KORNAME", resourceCulture);
            }
        }
    }
}
